package jlox.scanner;

/**
 * A token which is generated by the Scanner and parsed by the parser.
 * 
 * @param lexeme  represents the raw lexeme.
 * @param type    represents the type of the token.
 * @param literal The token literal (i.e. String or number).
 * @param line    The line number at which the token appears.
 */
public class Token {
  public final String lexeme;
  public final TokenType type;
  public final Object literal;
  public final int line;

  public Token(String lexeme, TokenType type, Object literal, int line) {
    this.lexeme = lexeme;
    this.type = type;
    this.literal = literal;
    this.line = line;
  }

  @Override
  public String toString() {
    return type + " " + lexeme + " " + literal;
  }
}